### ISSUE TITLE
Clarify what page URLs are and how to use them

### ISSUE THREAD

**Issue by HankG** [diaspora/api-documentation#13]
I'm reading over the API guide as I'm embarking on filling out the implementation and I am confused about what is going to support pagination and what is not.  Questions that are coming to mind as I try to grok it are:

Is that something we want to highlight or is it something that a client library should always assume will be coming down the response.  Is it something where there is a body of response and the link block thus if they don't handle the link block they will just get whatever the default body set is?

Are these "first, previous, next, last" returning pages or items?  I'm guessing pages otherwise this is going to be very chatty with the server.  The thing that threw me was the statement that instead of pages it may use timestamps.  I think that is just a generic "don't expect the ?page=# format because the relative link could look radically different" and with something like dates it could be date ranges even or something like that.

Are the max number of elements back per page something that will be server or request configurable, or both?  Like a client library could ask for 5 elements back instead of a default of 20 but if they ask for one billion back it's not going to send back more than 100?  Even if we think this sort of thing would be great eventually I'd say for an MVP V1 we don't need to support that necessarily.  For pages it'd be easy, for something that does stuff based on date ranges or something it would get more complicated quickly.

**Comment by skyschub** [comment]
> Is that something we want to highlight or is it something that a client library should always assume will be coming down the response.

You are right, we should add a note to routes that could respond with paginated results.

> Are these "first, previous, next, last" returning pages or items?

Pages, yes. And because you had to ask this question, we should clarify that.

>  I think that is just a generic "don't expect the ?page=# format because the relative link could look radically different" and with something like dates it could be date ranges even or something like that.

This should probably be a "don't assume anything and just query the URLs we provide". Would that make it clearer?

> Are the max number of elements back per page something that will be server or request configurable, or both?

Filed #24 for that.

**Comment by skyschub** [comment]
I've renamed the issue to track clarifying the URLs, and filed a second issue for adding a `per_page` param. Let's try to keep issues to one-actionable-item-per-issue. :)

**Comment by HankG** [comment]
> This should probably be a "don't assume anything and just query the URLs we provide". Would that make it clearer?

I believe the current documentation already provides appropriate warning.
