### ISSUE TITLE
Mention referencing example in posts text is not correct

### ISSUE THREAD

**Issue by HankG** [diaspora/api-documentation#22]
The text necessary for mentioning another user in a post needs to be corrected to work.  The sample text was used against the "bob" user in tests and failed while the Diaspora handle worked.  I don't know if searching by e-mail address works or not in a reference but should have something is confirmed working.

**Comment by SuperTux88** [comment]
Nice catch, thank you :cookie: Mention only works by diaspora ID, not by e-mail address.

**Comment by skyschub** [comment]
Fixed! :)
