### ISSUE TITLE
Add per_page parameter to global pagination

### ISSUE THREAD

**Issue by skyschub** [diaspora/api-documentation#24]
The pagination system should support a `per_page` parameter to allow clients how many entities the endpoint should return. This parameter needs to be clamped to some boundaries, `[1,100]` feels like a good start. However, for stream queries, we might limit that to something like `[1,20]` to avoid heavy server load, but this is probably best decided when implementing the endpoints.

**Comment by HankG** [comment]
Implementation of paging incorporates this now. Will polish up documentation to reflect it.
