### ISSUE TITLE
Streams Endpoint tags documents should referenc Tags-Search feature in "See Also" section

### ISSUE THREAD

**Issue by HankG** [diaspora/api-documentation#27]
The Tags method as specified only does the top level tags (all tags).  The UI allows a user to select a specific tag that they would like to request a stream on.  Whether that should be an array of tags that are then aggregated or one at a time is TBD.  The current Aspects method takes an array of aspects even though the UI only allows one to look at a stream with one at a time.  I'm inclined to make the Tags method work the same as the Aspects one.

**Comment by Flaburgan** [comment]
>The current Aspects method takes an array of aspects even though the UI only allows one to look at a stream with one at a time

Nope, diaspora* UI allows you to select one or several aspects to be displayed in the stream (in fact, when you click on My aspects, they are all checked). It does not, however, allow you to select multiple tags at the same time, as when you click on one in the "followed tag" subsection in the left column, you are redirected to that tag own page.

In the case of the API, I see no problem for it being an array.

**Comment by HankG** [comment]
@Flaburgan I see what you are saying about the aspects.  I'm not worried about the Aspects method though but the Tags one.  

Currently there is no way to pull for a followed tag in the endpoint. One can only pull for all followed tags.  In the UI one can select one of their followed tags and pull get a stream from that.  I see that if we add the ability to have them pick a followed tag that it would be one tag at a time if it is to follow the UI feature set.  Whether it is one tag at a time as in the UI or multiple tags at one time I'm more ambivalent on.  It'll probably be easy to implement as one tag at a time since the other controllers/services already support one at a time.

**Comment by SuperTux88** [comment]
To get posts for only one tag there is this: https://diaspora.github.io/api-documentation/routes/search.html#search-for-posts

**Comment by HankG** [comment]
> To get posts for only one tag there is this: https://diaspora.github.io/api-documentation/routes/search.html#search-for-posts

That's actually even more flexible since the followed tags has to be a followed tags.  Are the returns going to be exactly the same?  If so I'll put a reference to it in the documentation as a "see" type of reference.

**Comment by SuperTux88** [comment]
That should return exactly what you see when you click on a tag on the current interface.
