### ISSUE TITLE
Add interactions to comments for likes

### ISSUE THREAD

**Issue by tclaus** [diaspora/api-documentation#61]
To implement https://github.com/diaspora/diaspora/pull/8203 a comment can have one or more likes.
A comment should have a interactions node, with a likes array and likes_count. Similar to post.interactions.
`"interactions": {
      "likes": [..],
      "likes_count": 42
  }`

Is this OK to extend a comment json this way?

<img width="339" alt="Bildschirmfoto 2021-02-12 um 19 55 19" src="https://user-images.githubusercontent.com/501326/107809990-3ea79e00-6d6c-11eb-932e-eb8d43a21a28.png">

**Comment by Flaburgan** [comment]
Yep looks good to me, and as @jhass also thumbed up I would say it's fine. Would you mind opening a pull request?

**Comment by tclaus** [comment]
Wat comes into my mind - for the API part, the like has an author, the author has an avatar, the avatar is an image, or a list of three different avatars. 
I think for the API the avatar may only be one image (the small one), and for the backbone(?) all thee kinds of profile images?
